import { Inter } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./Components/ProviderWrapper/ProviderWrapper";
import RouteController from "./Components/RouteController/RouteController";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
          <RouteController>{children}</RouteController>
        </ProviderWrapper>
      </body>
    </html>
  );
}
